server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.zzlhs.microservice.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
 
spring:
  application:
    name: microservicecloud-dept #消费者调用的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    username: root 
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001 #设置自己在注册中心的别名
    prefer-ip-address: true #访问路径可以显示ip地址
   
info:
  app.name: zzlhs-microservicecloud
  company.name: www.zzlhs.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT
  